Repository deep-voice/soundbay, pull requests merged in 2024-01, with the labels that each got.

#84 Feature/download lists dropbox
  scripts/download_dropbox_folder.py
Labels: ci-test

#85 Bugfix/check file before url
  scripts/download_dropbox_folder.py
Labels: ci-test

#86 [auxiliary][spectrogram_visualizer]
  notebooks/spectrogram_visualizer.ipynb
Labels: enhancement, ci-test

#87 [BUGFIX][_slice_sequence]
  soundbay/data.py
Labels: bug, ci-test
